In [ ]:
number=16
type(number)

int

In [ ]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes

In [ ]:
my_list=[1,2,3]
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
#numpy

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
array_1_=np.array([1,2,3,4])
array_2_=np.array([.5,1.5,3,7.0])

In [ ]:
print(array_1_[0])
print(array_2_[:3])

1
[0.5 1.5 3. ]


In [ ]:
array_2_[-1]

7.0

In [ ]:
print(array_1_.dtype)
print(array_2_.dtype)
empty_=np.array([])
print(empty_.dtype)# empty has an attribute that default dtype is  float

int64
float64
float64


In [ ]:
np.array([1,2,3,4],dtype=np.float_)

array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4],dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [ ]:
b_=np.array(["ada","lovelae"])

In [ ]:
b_.dtype

dtype('<U7')

In [ ]:
#Dimension and Shape

In [ ]:
my_array=np.array([[1,2,4],[5,6,7]])

In [ ]:
print(my_array.shape)
print(my_array.ndim)
print(my_array.size)

(2, 3)
2
6


In [ ]:
my_array=np.array([[1,2,4],[5,6,7],[7,9,10]])

In [ ]:
my_array[1]

array([5, 6, 7])

In [ ]:
my_array[1][0]

5

In [ ]:
my_array[1,0]

5

In [ ]:
my_array[0:2]

array([[1, 2, 4],
       [5, 6, 7]])

In [ ]:
my_array[:2,:2]

array([[1, 2],
       [5, 6]])

In [ ]:
my_array[1]=np.array([10,10,10])

In [ ]:
my_array

array([[ 1,  2,  4],
       [10, 10, 10],
       [ 7,  9, 10]])

In [ ]:
my_array[2]=99
my_array

array([[ 1,  2,  4],
       [10, 10, 10],
       [99, 99, 99]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
my_array=np.arange(0,10)

In [ ]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.arange(1.,10.1,3)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones((2,5,3))#

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
my_array=np.random.random((5,2))

In [ ]:
my_array

array([[0.15685534, 0.28325861],
       [0.37681466, 0.39432826],
       [0.73575174, 0.44337982],
       [0.11644768, 0.62124273],
       [0.08407664, 0.66987772]])

In [ ]:
my_array[0]

array([0.15685534, 0.28325861])

In [ ]:
np.random.randint(100,size=(5,2))

array([[18, 32],
       [80, 80],
       [44, 44],
       [89,  1],
       [46,  9]])

In [ ]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
array_1=np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array_1=array_1.reshape(2,5)

In [ ]:
np.concatenate([array_1,array_1],axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [ ]:
array_1=np.arange(0,20)
array_1=array_1.reshape(5,4)

In [ ]:
array_1.sum()

190

In [ ]:
array_1.mean()

9.5

In [ ]:
array_1.std()

5.766281297335398

In [ ]:
array_1.var()

33.25

In [ ]:
array_1.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [ ]:
array_1 += 10
array_1

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [ ]:
array_2=np.arange(0,10)
array_2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
array_2 +=10

In [ ]:
array_2

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
array_2[0],array_2[-1]

(30, 39)

In [ ]:
array_2[[0,-1]]

array([30, 39])

In [ ]:
a=np.arange(4)

In [ ]:
a[[True,False,False,True]]

array([0, 3])

In [ ]:
seri=a.mean()

In [ ]:
a[a>[seri]]

array([2, 3])

In [ ]:
a[(a==0) |(a==1)]

array([0, 1])

In [ ]:
a[(a<=2)&(a%2==0)]

array([0, 2])

In [ ]:
# 100 e kadar rastgele tam sayılardan oluşan 3,3 lük bir matris oluştur
# 30 dan büyük olanları boolean yöntemi ile filtrele

In [ ]:
rand_arra=np.random.randint(100,size=(3,3))


In [ ]:
rand_arra[rand_arra>30]

array([48, 69, 47, 89, 83, 43])

In [124]:
my_array=np.array([0,1,2,3,4,5,6,7,8,9])
array_1=my_array.reshape(5,2)
array_2=my_array.reshape(2,5)

In [125]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [126]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
np.dot(array_1,array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [128]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [129]:
import sys

In [130]:
sys.getsizeof(10)

28

In [131]:
sys.getsizeof(1000**100)

160

In [132]:
np.dtype(np.int).itemsize

8

In [135]:
np.dtype(np.int8).itemsize

1

In [136]:
np.dtype(float).itemsize

8

In [137]:
sys.getsizeof([1,2,3])

88

In [138]:
np.array([1,2,3]).nbytes

24

In [139]:
my_list=list(range(10000))

In [141]:
my_array=np.arange(10000)

In [142]:
%time np.sum(my_array**2)

CPU times: user 1.29 ms, sys: 0 ns, total: 1.29 ms
Wall time: 1.25 ms


333283335000

In [143]:
%time np.sum([number**2 for number in my_list])

CPU times: user 4.45 ms, sys: 935 µs, total: 5.38 ms
Wall time: 5.39 ms


333283335000